### ISSUE TITLE
Would Love to Try This

### ISSUE THREAD

**Issue by jmcbri** [bullet-train-co/stimulus-debug#1]
Any plans to mod for Stimulus 3?

**Comment by pascallaliberte** [comment]
@jmcbri 

With [newer versions of Stimulus having debugging baked in](https://stimulus.hotwired.dev/handbook/installing#debugging), this library is probably no longer useful. It does serve a different pattern however...

Have you tried the default debugging?

**Comment by jmcbri** [comment]
@pascallaliberte 
THANKS for responding!  Just learning about the debugging.

**Comment by jmcbri** [comment]
Obviously, you can close this.  Also, I tried to find a way to contribute $10 to you for answering. (Yes, it's not enough) but I didn't see a way.  If there is, advise me.

**Comment by pascallaliberte** [comment]
Hi @jmcbri, that's so thoughtful of you. No need!
If you haven't done so already, please give https://bullettrain.co a spin.
